ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'DARK';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'MODERN_GREEN';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'MULTI_COLOR_BLOCK';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'PAPER_MINT';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'AMBER_LEDGER';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'OCEAN_INK';
