ALTER TABLE "Goal"
ADD COLUMN "isShared" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Project"
ADD COLUMN "pinToDashboard" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "MaintenanceRecord"
ADD COLUMN "pinToDashboard" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "CalendarEvent"
ADD COLUMN "pinToDashboard" BOOLEAN NOT NULL DEFAULT false;
