ALTER TABLE "Goal"
ADD COLUMN IF NOT EXISTS "isShared" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Project"
ADD COLUMN IF NOT EXISTS "pinToDashboard" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "MaintenanceRecord"
ADD COLUMN IF NOT EXISTS "pinToDashboard" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "CalendarEvent"
ADD COLUMN IF NOT EXISTS "pinToDashboard" BOOLEAN NOT NULL DEFAULT false;
