ALTER TABLE "Goal"
ADD COLUMN IF NOT EXISTS "notificationTime" TEXT,
ADD COLUMN IF NOT EXISTS "lastNotificationSentAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "notificationCooldownHours" INTEGER NOT NULL DEFAULT 24;

ALTER TABLE "Task"
ADD COLUMN IF NOT EXISTS "notificationTime" TEXT,
ADD COLUMN IF NOT EXISTS "lastNotificationSentAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "notificationCooldownHours" INTEGER NOT NULL DEFAULT 24;

ALTER TABLE "ProjectTask"
ADD COLUMN IF NOT EXISTS "notificationTime" TEXT,
ADD COLUMN IF NOT EXISTS "lastNotificationSentAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "notificationCooldownHours" INTEGER NOT NULL DEFAULT 24;

ALTER TABLE "HouseworkItem"
ADD COLUMN IF NOT EXISTS "notificationTime" TEXT,
ADD COLUMN IF NOT EXISTS "lastNotificationSentAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "notificationCooldownHours" INTEGER NOT NULL DEFAULT 24;

ALTER TABLE "MaintenanceRecord"
ADD COLUMN IF NOT EXISTS "notificationTime" TEXT,
ADD COLUMN IF NOT EXISTS "lastNotificationSentAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "notificationCooldownHours" INTEGER NOT NULL DEFAULT 24;

ALTER TABLE "CalendarEvent"
ADD COLUMN IF NOT EXISTS "notificationTime" TEXT,
ADD COLUMN IF NOT EXISTS "lastNotificationSentAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "notificationCooldownHours" INTEGER NOT NULL DEFAULT 24;
