DO $$ BEGIN
    CREATE TYPE "TaskType" AS ENUM ('TASK', 'PAYMENT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "taskType" "TaskType" NOT NULL DEFAULT 'TASK';
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "expenseCategory" TEXT;
