
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password: 'password',
  role: 'role',
  active: 'active',
  theme: 'theme',
  notificationEnabled: 'notificationEnabled',
  notificationChannel: 'notificationChannel',
  notificationEmail: 'notificationEmail',
  timezone: 'timezone',
  telegramChatId: 'telegramChatId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  userId: 'userId',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.GoalScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  userId: 'userId',
  periodType: 'periodType',
  targetCount: 'targetCount',
  currentCount: 'currentCount',
  currentPeriodStart: 'currentPeriodStart',
  startDate: 'startDate',
  active: 'active',
  notificationEnabled: 'notificationEnabled',
  pinToDashboard: 'pinToDashboard',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GoalCheckInScalarFieldEnum = {
  id: 'id',
  goalId: 'goalId',
  userId: 'userId',
  quantity: 'quantity',
  note: 'note',
  date: 'date',
  createdAt: 'createdAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  userId: 'userId',
  isShared: 'isShared',
  dueDate: 'dueDate',
  priority: 'priority',
  status: 'status',
  notificationEnabled: 'notificationEnabled',
  pinToDashboard: 'pinToDashboard',
  sortOrder: 'sortOrder',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  category: 'category',
  deadline: 'deadline',
  priority: 'priority',
  status: 'status',
  assigneeId: 'assigneeId',
  createdById: 'createdById',
  notificationEnabled: 'notificationEnabled',
  pinToDashboard: 'pinToDashboard',
  kanbanOrder: 'kanbanOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LearningItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  subject: 'subject',
  target: 'target',
  progress: 'progress',
  deadline: 'deadline',
  status: 'status',
  userId: 'userId',
  notificationEnabled: 'notificationEnabled',
  pinToDashboard: 'pinToDashboard',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IdeaScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  category: 'category',
  tags: 'tags',
  status: 'status',
  userId: 'userId',
  pinToDashboard: 'pinToDashboard',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HouseworkItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  assigneeId: 'assigneeId',
  createdById: 'createdById',
  frequencyType: 'frequencyType',
  customIntervalDays: 'customIntervalDays',
  nextDueDate: 'nextDueDate',
  lastCompletedDate: 'lastCompletedDate',
  estimatedCost: 'estimatedCost',
  notificationEnabled: 'notificationEnabled',
  pinToDashboard: 'pinToDashboard',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AssetScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  brand: 'brand',
  model: 'model',
  serialNumber: 'serialNumber',
  purchaseDate: 'purchaseDate',
  note: 'note',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MaintenanceRecordScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  serviceDate: 'serviceDate',
  description: 'description',
  serviceType: 'serviceType',
  cost: 'cost',
  vendor: 'vendor',
  nextRecommendedDate: 'nextRecommendedDate',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CalendarEventScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  startDate: 'startDate',
  endDate: 'endDate',
  allDay: 'allDay',
  location: 'location',
  color: 'color',
  category: 'category',
  isShared: 'isShared',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventParticipantScalarFieldEnum = {
  id: 'id',
  eventId: 'eventId',
  userId: 'userId'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  date: 'date',
  description: 'description',
  amount: 'amount',
  category: 'category',
  scope: 'scope',
  note: 'note',
  recurring: 'recurring',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AlertRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  moduleType: 'moduleType',
  frequency: 'frequency',
  dayOfWeek: 'dayOfWeek',
  dayOfMonth: 'dayOfMonth',
  time: 'time',
  conditionType: 'conditionType',
  conditionValue: 'conditionValue',
  cooldownHours: 'cooldownHours',
  lastSentAt: 'lastSentAt',
  notificationChannel: 'notificationChannel',
  active: 'active',
  sortOrder: 'sortOrder',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScheduledReportScalarFieldEnum = {
  id: 'id',
  name: 'name',
  reportType: 'reportType',
  dateRangePreset: 'dateRangePreset',
  frequency: 'frequency',
  dayOfMonth: 'dayOfMonth',
  dayOfWeek: 'dayOfWeek',
  time: 'time',
  sections: 'sections',
  notificationChannel: 'notificationChannel',
  recipients: 'recipients',
  active: 'active',
  sortOrder: 'sortOrder',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BudgetSettingScalarFieldEnum = {
  id: 'id',
  category: 'category',
  period: 'period',
  amount: 'amount',
  active: 'active',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TelegramLinkScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  telegramChatId: 'telegramChatId',
  telegramUserId: 'telegramUserId',
  telegramUsername: 'telegramUsername',
  linkCode: 'linkCode',
  linkCodeExpiresAt: 'linkCodeExpiresAt',
  verifiedAt: 'verifiedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AssistantMessageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  channel: 'channel',
  externalMessageId: 'externalMessageId',
  direction: 'direction',
  rawText: 'rawText',
  normalizedText: 'normalizedText',
  intent: 'intent',
  confidence: 'confidence',
  createdAt: 'createdAt'
};

exports.Prisma.AssistantActionLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  channel: 'channel',
  intent: 'intent',
  confidence: 'confidence',
  requestPayload: 'requestPayload',
  resolvedEntities: 'resolvedEntities',
  executionStatus: 'executionStatus',
  resultSummary: 'resultSummary',
  errorMessage: 'errorMessage',
  createdAt: 'createdAt'
};

exports.Prisma.AssistantPendingActionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  channel: 'channel',
  intent: 'intent',
  payload: 'payload',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};
exports.Role = exports.$Enums.Role = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  USER: 'USER'
};

exports.Theme = exports.$Enums.Theme = {
  BLUE_PURPLE: 'BLUE_PURPLE',
  GREY_BLACK: 'GREY_BLACK',
  RED_ACCENT: 'RED_ACCENT'
};

exports.NotificationChannel = exports.$Enums.NotificationChannel = {
  EMAIL: 'EMAIL',
  TELEGRAM: 'TELEGRAM',
  BOTH: 'BOTH'
};

exports.PeriodType = exports.$Enums.PeriodType = {
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY'
};

exports.Priority = exports.$Enums.Priority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.ProjectStatus = exports.$Enums.ProjectStatus = {
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  ARCHIVED: 'ARCHIVED'
};

exports.IdeaStatus = exports.$Enums.IdeaStatus = {
  OPEN: 'OPEN',
  REVIEWING: 'REVIEWING',
  ARCHIVED: 'ARCHIVED'
};

exports.FrequencyType = exports.$Enums.FrequencyType = {
  ONE_TIME: 'ONE_TIME',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  HALF_YEARLY: 'HALF_YEARLY',
  YEARLY: 'YEARLY',
  CUSTOM: 'CUSTOM'
};

exports.ExpenseScope = exports.$Enums.ExpenseScope = {
  PERSONAL: 'PERSONAL',
  FAMILY: 'FAMILY'
};

exports.AlertFrequency = exports.$Enums.AlertFrequency = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY'
};

exports.ReportFrequency = exports.$Enums.ReportFrequency = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY'
};

exports.BudgetPeriod = exports.$Enums.BudgetPeriod = {
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY'
};

exports.AssistantChannel = exports.$Enums.AssistantChannel = {
  TELEGRAM: 'TELEGRAM'
};

exports.MessageDirection = exports.$Enums.MessageDirection = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND'
};

exports.ExecutionStatus = exports.$Enums.ExecutionStatus = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  CANCELLED: 'CANCELLED'
};

exports.Prisma.ModelName = {
  User: 'User',
  RefreshToken: 'RefreshToken',
  Goal: 'Goal',
  GoalCheckIn: 'GoalCheckIn',
  Task: 'Task',
  Project: 'Project',
  LearningItem: 'LearningItem',
  Idea: 'Idea',
  HouseworkItem: 'HouseworkItem',
  Asset: 'Asset',
  MaintenanceRecord: 'MaintenanceRecord',
  CalendarEvent: 'CalendarEvent',
  EventParticipant: 'EventParticipant',
  Expense: 'Expense',
  AlertRule: 'AlertRule',
  ScheduledReport: 'ScheduledReport',
  BudgetSetting: 'BudgetSetting',
  TelegramLink: 'TelegramLink',
  AssistantMessage: 'AssistantMessage',
  AssistantActionLog: 'AssistantActionLog',
  AssistantPendingAction: 'AssistantPendingAction'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
