ALTER TABLE "Task"
ADD COLUMN IF NOT EXISTS "scope" "ExpenseScope" NOT NULL DEFAULT 'PERSONAL';

ALTER TABLE "LearningTopic"
ADD COLUMN IF NOT EXISTS "category" TEXT;

ALTER TABLE "Idea"
ADD COLUMN IF NOT EXISTS "field" TEXT;
